spring:

  application:
    name: attendance-system

  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    username: postgres
    password: 231429

  jpa:
    hibernate:
      ddl-auto: update

server:
   port: 8081

jwt:
   secret: 12345678901234567890123456789012
   expiration: 86400000
